source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

def shared_pods
	pod 'SCPageViewController', :path => '../'
end

target 'ObjCDemo' do
	shared_pods
end

target 'Tests' do
	shared_pods
end

target 'SwiftDemo' do
	shared_pods
end